### ISSUE TITLE
Remove RequireJS dependency

### ISSUE THREAD

**Issue by SiAdcock** [Jameskmonger/courtroom#15]
It would be really good to eliminate the RequireJS dependency, so users aren't forced down the AMD route. 

Could potentially use one of the [UMD templates](https://github.com/umdjs/umd/tree/master/templates)

**Comment by Jameskmonger** [comment]
Sounds good - this would let it be used server-side as-is!

**Comment by jamesrichford** [comment]
Thanks to lovely TypeScript this is trivial - simply set another build type with module umd, no reason you can't have system and commonjs (am using system atm in some of my projects so would appreciate it ;) )

https://github.com/Microsoft/TypeScript/wiki/Compiler-Options

**Comment by SiAdcock** [comment]
:+1: @jamesrichford

**Comment by Jameskmonger** [comment]
:ok: :cool:

**Comment by SiAdcock** [comment]
From what I've learned, the transpile needs to happen either:

1) before a contributor commits, with the contributor running a gulp/grunt task or script (so generated JS gets checked into the repo, which is less than ideal) OR 
2) using a CI script that runs when the library is published on NPM. This appears to be the way Angular2 do it.

Also I'd suggest using UMD rather than SystemJS as it is less opinionated. From what I understand SystemJS (as well as Node, RequireJS, Browserify and Webpack) can load UMD modules.

**Comment by Jameskmonger** [comment]
Yeah, I'd be more comfortable with only pushing the "source" (TypeScript) code into the repo @SiAdcock

**Comment by SiAdcock** [comment]
:+1:

**Comment by Jameskmonger** [comment]
Fixed in 16f5f286092aba88e92beb59bd57df6699a83324 - we now use UMD to publish to NPM.
