### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by SiAdcock** [Jameskmonger/courtroom#16]
Looks like the name `courtroom` is not taken yet!

https://registry.npmjs.org/courtroom

Might be worth dropping the version number down to < 1.0.0 to indicate that the package is still under heavy development and has not stabilised yet.

**Comment by Jameskmonger** [comment]
:+1: Will look at this later

**Comment by Jameskmonger** [comment]
Hi @SiAdcock, what's normally published to NPM? Just production code? Just source code? Or both?

**Comment by SiAdcock** [comment]
Most folks publish both.

**Comment by Jameskmonger** [comment]
Done! I did a bit of research and decided to only publish the production code for now, but included repository info in the package.

https://www.npmjs.com/package/courtroom

**Comment by SiAdcock** [comment]
Cool! Production's the important bit :smile:
