### ISSUE TITLE
Rename "Jury" to "Law"

### ISSUE THREAD

**Issue by SiAdcock** [Jameskmonger/courtroom#32]
This might sound a bit pedantic, but why are validation rules called Juries and not Laws? I'm no law student, but to me it doesn't make sense that a Lawbook contains a collection of Juries, when it seems more natural that it should have a collection of Laws. When I was first reading the code, I struggled a bit with the Jury concept, wondering where it fitted. 

Also the documentation makes no mention of Jury. Is this something that you are looking to refactor anyway?

**Comment by Jameskmonger** [comment]
No reason at all - infact I think that law would be a better name for it! I've renamed this issue accordingly :smile:
